- name: creating jobs for roboshop project
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - demo
    pipeline_jobs:
     - { jobName: "sample009", folderName: "demo", repoName: "learning-jenkins"}

