- name: creating jobs for roboshop project
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - App-Setup-Ansible
    pipeline_jobs:
     - { jobName: "roboshop", folderName: "App-Setup-Ansible", repoName: "roboshop-ansible"}

