- name: creating jobs for roboshop project
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - App-Setup-Ansible
      - infrastrutre
    pipeline_jobs:
     - { jobName: "roboshop", folderName: "App-Setup-Ansible", repoName: "roboshop-ansible", FileName: "Jenkinsfile"}
     - { jobName: "cart", folderName: "infrastrutre", repoName: "cart-infra", FileName: "Jenkinsfile"}
     - { jobName: "user", folderName: "infrastrutre", repoName: "user-infra", FileName: "Jenkinsfile"}
     - { jobName: "payment", folderName: "infrastrutre", repoName: "payment-infra", FileName: "Jenkinsfile"}
     - { jobName: "shipping", folderName: "infrastrutre", repoName: "shipping-infra", FileName: "Jenkinsfile"}
     - { jobName: "frontend", folderName: "infrastrutre", repoName: "frontend-infra", FileName: "Jenkinsfile"}
     - { jobName: "catalogue", folderName: "infrastrutre", repoName: "catalogue-infra", FileName: "Jenkinsfile"}
     - { jobName: "DESTROY", folderName: "infrastrutre", repoName: "roboshop-jenkins", FileName: "Jenkinsfile-destroy-infra"}
     - { jobName: "transit-tgw", folderName: "infrastrutre", repoName: "terraform-vpc-transit-setup", FileName: "Jenkinsfile"}
