- name: creating jobs for roboshop project
  hosts: localhost
  roles:
    - jenkins-jobs
  vars:
    folders:
      - App-Setup-Ansible
      - infrastrutre
    pipeline_jobs:
     - { jobName: "roboshop", folderName: "App-Setup-Ansible", repoName: "roboshop-ansible"}
     - { jobName: "cart", folderName: "infrastrutre", repoName: "cart-infra"}

