- name: Create a folder inside jenkins
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    password: admin
    url: http://172.31.12.209:8080
    user: admin
  loop: "{{folders}}"


- name: create a pipeline job
  include_role:
    name: jenkins-jobs
    tasks_from: pipeline-jobs
  loop: "{{pipeline_jobs}}"

