- name: temlating a pipeline-job xml file
  template:
    src: pipeline-jobs.xml
    dest: /tmp

- name: check if job exits or not
  community.general.jenkins_job_info:
    name: "{{item.folderName}}/{{item.jobName}}"
    password: admin
    url: http://172.31.12.209:8080
    user: admin
  register: job_info
  ignore_errors: yes


- name: Create a jenkins job using for roboshop
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/pipeline-jobs.xml') }}"
    name: "{{item.folderName}}/{{item.jobName}}"
    password: admin
    url: http://172.31.12.209:8080
    user: admin
  when: job_info.failed
